### ISSUE TITLE
White space in Tooltips leading to multiple lines

### ISSUE THREAD

**Issue by mju516** [leongersen/wnumb#16]
Hello. I'm attempting to format a string for use with the tooltip, but I've noticed that whitespace will cause the text to go to multiple lines.

Please see the following fiddle: https://jsfiddle.net/jpk6r7ye/1/

If you uncomment the CSS, the text will go to a single line, but the box will not be formatted nicely. Any ideas for this?

**Comment by leongersen** [comment]
You could use non-breaking spaces: `'\u00A0' + '(US' + '\u00A0' + '$)'`
