### ISSUE TITLE
Rounding issue

### ISSUE THREAD

**Issue by barbedCoil** [leongersen/wnumb#18]
**Data**
I have the following value going into wNumb:  **8.905**

**Format**
Here is the wNum function setup:

`            moneyFormat: wNumb({
                mark: ".",
                thousand: ",",
                decimals: 2,
                prefix: "$",
                postfix: ""
            }),
`

**Expected Result**
I am expecting **$8.91** as the output value

**Actual Result**
I am getting **$8.90** as the output value

To me this seems like an issue where it is not rounding correctly with 5 as the 3rd decimal digit I would expect it to round the 2nd digit to 1 instead of leave at 0 since I am specifying 2 Decimal places.

Interestingly, wNumb does a better job of rounding than C# does but it is always cases like this that do not round correctly #.#05 where # is a digit

Thoughts?

**Comment by leongersen** [comment]
`8.905` is `8.9049999999999993605115378159098327159881591796875` when represented as a double. wNumb already tries to work around this, but it's apparently not accurate enough. I'll see if there is something I can do to round this more accurately.

**Comment by leongersen** [comment]
Fixed (with tests) in release 1.1. Thanks for reporting!

**Comment by barbedCoil** [comment]
Excellent. Thanks

On February 4, 2017 5:01:38 AM MST, Leon Gersen <notifications@github.com> wrote:
>Fixed (with tests) in release 1.1. Thanks for reporting!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/leongersen/wnumb/issues/18#issuecomment-277440098

-- 
Tab
