### ISSUE TITLE
`suffix` not working, but `postfix` does

### ISSUE THREAD

**Issue by wardpenney** [leongersen/wnumb#19]
Hi Leon, cool library! I just noticed that `suffix` appears to not work, but `postfix` does.

Here is my source from an implementation of your [noUISlider](https://github.com/leongersen/noUiSlider).

```
var tooltipFormat = wNumb({
  decimals: 0,
  decoder: function(number){
    return number * 1000;
  },
  encoder: function(number){
    return number / 1000;
  },
  prefix: "$",
  postfix: "k"
})

var salaryRangeSlider = $("#my-slider")[0];
noUiSlider.create(salaryRangeSlider, {
  start: [10000, 225000],
  connect: true,
  tooltips: [tooltipFormat, tooltipFormat],
  range: {
    "min": [10000, 10000],
    "64%": [100000, 25000],
    "max": [250000]
  }
});
```

Everything looks good in the tooltip, and it says `$200k`. However, when the `postfix` above is changed to `suffix` the `k` is never output into the tooltip. 

Let me know if you would like more info!

Regards,
W

**Comment by leongersen** [comment]
`Postfix` was renamed to `suffix` in 1.1 (although it is backward compatible). Did you upgrade?

**Comment by wardpenney** [comment]
I downloaded the one from https://refreshless.com/wnumb/ looks like 1.0.2. I'll upgrade. Would you consider updating that link to just go to the repo? Thanks.

**Comment by leongersen** [comment]
I should fix that!
