### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by evilebottnawi** [leongersen/wnumb#21]
Package contains unnecessary file - `test.html`. I can do PR if your accept this issue.

**Comment by pankajpatel** [comment]
This file is for tests. Though the tests can be moved to npm scripts with some quick and simple testing library like `tape`.

If this file doesn't reach the final bundle then it should be fine.

**Comment by leongersen** [comment]
I've added a `files` directive to the package. Thanks for reporting.
