### ISSUE TITLE
Sometimes rounding goes wrong

### ISSUE THREAD

**Issue by dubaua** [leongersen/wnumb#25]
Here is my fiddle with problem.
https://jsfiddle.net/9nd5x348/6/
When I turn off wNumb formatting problem disappears

**Comment by leongersen** [comment]
When you add wNumb to your noUiSlider, there no longer is a default number of decimals. You should add them manually.

[Updated fiddle](https://jsfiddle.net/leongersen/9nd5x348/8/).
