### ISSUE TITLE
wNumb decimal doesn't work :( 

### ISSUE THREAD

**Issue by QuDDoSS** [leongersen/wnumb#26]
wNumb decimal doesn't work :( , i set decimal options with 0/false , and he return for example: 2.9999999, 5.99999996 ....

**Comment by PierreAdrienDelisle** [comment]
Same problem here with great numbers like '431 000' that become '430 999.99999999994'. However I did the decimal to 0

**Comment by AugmentBLU** [comment]
Same here.

**Comment by leongersen** [comment]
Are you on wNumb 1.0.1 or above?

**Comment by AugmentBLU** [comment]
Yes, latest. I just found this function that works though.

```
   encoder: (value) => {
    	return Math.floor(value)
    }
```

**Comment by leongersen** [comment]
What specific example with decimals 0 does not work?

```
// "431000"
wNumb({ decimals: 0 }).to(431000)
```
