### ISSUE TITLE
Register with Bower?

### ISSUE THREAD

**Issue by jrp90** [leongersen/wnumb#5]
Hi there,

I'm currently using your nouislider which is registered on bower but I can't find the wnumb formatter extension on there.

Is there any chance you can register that one too?

Thanks :)

James

**Comment by leongersen** [comment]
It is included in the file published for noUiSlider: `jquery.nouislider.all.min.js` includes both libLink and wNumb.

**Comment by jrp90** [comment]
Ah ok, I must've missed that. Thanks!

**Comment by leongersen** [comment]
Happy to help :)
