### ISSUE TITLE
incorrect decimals: 0 behaviour

### ISSUE THREAD

**Issue by Pewpeller** [leongersen/wnumb#8]
I guess there is mistake in the code, in case of decimals set to 0.

		// Reduce the number of decimals to the specified option.
		if ( decimals ) {
			input = toFixed( input, decimals );
		}

And the fix:
		// Reduce the number of decimals to the specified option.
		if ( typeof decimals != 'undefined') {
			input = toFixed( input, decimals );
		}

Correct me, if i'm wrong. Thanks.

**Comment by leongersen** [comment]
This issue has been [fixed](https://github.com/leongersen/wnumb/commit/3a5e1bb5d5993b8129e4f9f530c776156526d955) a while back; I only just figured out that the download link in the documentation points to an unfixed version. I'll update it, thanks for the heads up!

**Comment by leongersen** [comment]
I fixed the doc, forgot to put it here. Thanks again!

**Comment by Pewpeller** [comment]
That was fast! Thanks a lot.
25 окт. 2015 г. 18:25 пользователь "Leon Gersen" <notifications@github.com>
написал:
